import { Menu } from "@/types";
import { ClientRoles } from "./others";

export default [
  {
    roles: [ClientRoles.OWNER, ClientRoles.MANAGER, ClientRoles.CATERING],
    key: "dashboard",
    label: "Dashboard",
    icon: "dashboard",
    url: "/dashboard",
  },
  {
    roles: [
      ClientRoles.OWNER,
      ClientRoles.MANAGER,
      ClientRoles.PRODUCTION,
      ClientRoles.PURCHASING,
      ClientRoles.CATERING,
    ],
    key: "metadata",
    label: "Metadata Management",
    icon: "layout-dashboard",
    subs: [
      {
        roles: [ClientRoles.OWNER, ClientRoles.MANAGER],
        key: "catering",
        label: "Catering Management",
        icon: "brand-itch",
        url: "/catering-management",
      },
      {
        roles: [ClientRoles.OWNER, ClientRoles.MANAGER, ClientRoles.PURCHASING],
        key: "material",
        label: "Material Management",
        icon: "cheese",
        url: "/material-management",
      },
      {
        roles: [ClientRoles.OWNER, ClientRoles.MANAGER],
        key: "product",
        label: "Product Management",
        icon: "soup",
        url: "/product-management",
      },
      {
        roles: [ClientRoles.OWNER, ClientRoles.MANAGER],
        key: "bom",
        label: "BOM Management",
        icon: "components",
        url: "/bom-management",
      },
      {
        roles: [ClientRoles.OWNER, ClientRoles.MANAGER],
        key: "unit",
        label: "Unit Management",
        icon: "currency-dollar",
        url: "/unit-management",
      },
      {
        roles: [ClientRoles.OWNER, ClientRoles.MANAGER, ClientRoles.PURCHASING],
        key: "supplier",
        label: "Supplier Management",
        icon: "truck",
        url: "/supplier-management",
      },
      {
        roles: [ClientRoles.OWNER, ClientRoles.MANAGER, ClientRoles.PRODUCTION],
        key: "customer",
        label: "Customer Management",
        icon: "address-book",
        url: "/customer-management",
        dashboard: [ClientRoles.OWNER],
      },
      {
        roles: [ClientRoles.OWNER, ClientRoles.CATERING],
        key: "meal",
        label: "Meal Management",
        icon: "fish",
        url: "/meal-management",
      },
      {
        roles: [ClientRoles.OWNER, ClientRoles.MANAGER],
        key: "user",
        label: "User Management",
        icon: "user-square",
        url: "/user-management",
      },
    ],
  },
  {
    roles: [
      ClientRoles.OWNER,
      ClientRoles.MANAGER,
      ClientRoles.PRODUCTION,
      ClientRoles.PURCHASING,
      ClientRoles.CATERING,
      ClientRoles.SUPPLIER,
    ],
    key: "purchasing-order-management",
    label: "Purchasing Order Management",
    icon: "shopping-cart",
    subs: [
      {
        roles: [
          ClientRoles.OWNER,
          ClientRoles.MANAGER,
          ClientRoles.PRODUCTION,
          ClientRoles.PURCHASING,
          ClientRoles.CATERING,
        ],
        key: "purchase-request-management",
        label: "Purchase Request Management",
        icon: "message-question",
        url: "/purchase-request-management",
      },
      {
        roles: [ClientRoles.OWNER, ClientRoles.SUPPLIER],
        key: "purchase-order-management",
        label: "Purchase Order Management",
        icon: "shopping-cart-check",
        url: "/purchase-order-management",
      },
      {
        roles: [ClientRoles.OWNER, ClientRoles.MANAGER, ClientRoles.PURCHASING],
        key: "purchase-internal-management",
        label: "Purchase Internal Management",
        icon: "package-import",
        url: "/purchase-internal-management",
      },
      {
        roles: [ClientRoles.OWNER, ClientRoles.SUPPLIER],
        key: "purchase-coordination-management",
        label: "Purchase Coordination Management",
        icon: "truck-loading",
        url: "/purchase-coordination-management",
      },
      {
        roles: [ClientRoles.OWNER, ClientRoles.MANAGER, ClientRoles.SUPPLIER],
        key: "supply-coordination",
        label: "Supply Coordination",
        icon: "affiliate",
        url: "/supply-coordination",
      },
    ],
  },
  {
    roles: [ClientRoles.OWNER, ClientRoles.MANAGER, ClientRoles.PURCHASING],
    key: "quotation-management",
    label: "Quotation Management",
    icon: "blockquote",
    subs: [
      {
        roles: [ClientRoles.OWNER, ClientRoles.MANAGER, ClientRoles.PURCHASING],
        key: "quotation-management",
        label: "Quotation Management",
        icon: "blockquote",
      },
      {
        roles: [ClientRoles.OWNER, ClientRoles.MANAGER, ClientRoles.PURCHASING],
        key: "quotation-history-management",
        label: "Quotation History Management",
        icon: "history",
      },
    ],
  },
  {
    roles: [
      ClientRoles.OWNER,
      ClientRoles.PRODUCTION,
      ClientRoles.CATERING,
      ClientRoles.PURCHASING,
    ],
    dashboard: [
      ClientRoles.PRODUCTION,
      ClientRoles.CATERING,
      ClientRoles.PURCHASING,
    ],
    key: "menu-management",
    label: "Menu Management",
    icon: "chef-hat",
    url: "/menu-management",
  },
  {
    roles: [
      ClientRoles.OWNER,
      ClientRoles.MANAGER,
      ClientRoles.ACCOUNTING,
      ClientRoles.PURCHASING,
    ],
    key: "payment-management",
    label: "Payment Management",
    icon: "receipt-2",
    subs: [
      {
        roles: [ClientRoles.OWNER, ClientRoles.MANAGER, ClientRoles.ACCOUNTING],
        key: "invoice-management",
        label: "Invoice Management",
        icon: "file-invoice",
      },
      {
        roles: [ClientRoles.OWNER, ClientRoles.MANAGER, ClientRoles.ACCOUNTING],
        key: "payment-request",
        label: "Payment Request",
        icon: "credit-card-pay",
      },
      {
        roles: [
          ClientRoles.OWNER,
          ClientRoles.MANAGER,
          ClientRoles.PURCHASING,
          ClientRoles.ACCOUNTING,
        ],
        key: "deviation-adjustment",
        label: "Deviation Adjustment",
        icon: "edit-circle",
        url: "/deviation-adjustment-management",
      },
      {
        roles: [ClientRoles.OWNER, ClientRoles.MANAGER, ClientRoles.ACCOUNTING],
        key: "payment-schedule",
        label: "Payment Schedule",
        icon: "credit-card-pay",
      },
      {
        roles: [ClientRoles.OWNER, ClientRoles.MANAGER, ClientRoles.ACCOUNTING],
        key: "cost-assignment",
        label: "Cost Assignment",
        icon: "plus-minus",
      },
    ],
  },
  {
    roles: [ClientRoles.OWNER, ClientRoles.MANAGER],
    key: "hrm-management",
    label: "HRM Management",
    icon: "id",
    subs: [
      {
        roles: [ClientRoles.OWNER, ClientRoles.MANAGER],
        key: "employee-management",
        label: "Employee Management",
        icon: "users",
      },
      {
        roles: [ClientRoles.OWNER, ClientRoles.MANAGER],
        key: "department-management",
        label: "Department Management",
        icon: "adjustments-horizontal",
      },
      {
        roles: [ClientRoles.OWNER, ClientRoles.MANAGER],
        key: "position-management",
        label: "Position Management",
        icon: "apps",
      },
    ],
  },
  {
    roles: [
      ClientRoles.OWNER,
      ClientRoles.MANAGER,
      ClientRoles.CATERING,
      ClientRoles.PURCHASING,
    ],
    key: "inventory-management",
    label: "Inventory Management",
    icon: "building-warehouse",
    subs: [
      {
        roles: [ClientRoles.OWNER, ClientRoles.MANAGER],
        key: "inventory-management",
        label: "Inventory List",
        icon: "package-import",
        url: "/inventory-management",
      },
      {
        roles: [ClientRoles.OWNER, ClientRoles.MANAGER, ClientRoles.CATERING],
        key: "check-inventory",
        label: "Check Inventory",
        icon: "checklist",
        url: "/check-inventory",
      },
      {
        roles: [ClientRoles.OWNER, ClientRoles.MANAGER, ClientRoles.PURCHASING],
        key: "inventory-transaction-details",
        label: "Inventory Transaction Details",
        icon: "transfer-in",
        url: "/inventory-transaction-details",
      },
      {
        roles: [ClientRoles.OWNER, ClientRoles.MANAGER, ClientRoles.PURCHASING],
        key: "warehouse-management",
        label: "Warehouse Management",
        icon: "list-details",
        url: "/warehouse-management",
      },
    ],
  },
  {
    roles: [
      ClientRoles.OWNER,
      ClientRoles.MANAGER,
      ClientRoles.ACCOUNTING,
      ClientRoles.PURCHASING,
      ClientRoles.CATERING,
    ],
    key: "report-management",
    label: "Report Management",
    icon: "report",
    subs: [
      {
        roles: [ClientRoles.OWNER, ClientRoles.MANAGER, ClientRoles.CATERING],
        key: "quick-report",
        label: "Quick Report",
        icon: "report-search",
      },
      {
        roles: [
          ClientRoles.OWNER,
          ClientRoles.MANAGER,
          ClientRoles.ACCOUNTING,
          ClientRoles.CATERING,
        ],
        key: "sales-report",
        label: "Sales Report",
        icon: "report-money",
      },
      {
        roles: [
          ClientRoles.OWNER,
          ClientRoles.MANAGER,
          ClientRoles.ACCOUNTING,
          ClientRoles.PURCHASING,
          ClientRoles.CATERING,
        ],
        key: "debt-report",
        label: "Debt Report",
        icon: "checkup-list",
      },
      {
        roles: [
          ClientRoles.OWNER,
          ClientRoles.MANAGER,
          ClientRoles.PURCHASING,
          ClientRoles.CATERING,
        ],
        key: "import-export-report",
        label: "Import - Export Report",
        icon: "report-analytics",
      },
      {
        roles: [ClientRoles.OWNER, ClientRoles.MANAGER, ClientRoles.CATERING],
        key: "report-template",
        label: "Report Templates",
        icon: "template",
      },
    ],
  },
  {
    roles: [ClientRoles.OWNER, ClientRoles.MANAGER],
    key: "system-settings",
    label: "System Settings",
    icon: "settings",
    subs: [
      {
        roles: [ClientRoles.OWNER, ClientRoles.MANAGER],
        key: "login-history",
        label: "Login History",
        icon: "template",
      },
      {
        roles: [ClientRoles.OWNER, ClientRoles.MANAGER],
        key: "access-authorization",
        label: "Access Authorization",
        icon: "login-2",
      },
      {
        roles: [ClientRoles.OWNER, ClientRoles.MANAGER],
        key: "function",
        label: "Function Management",
        icon: "box-multiple",
      },
    ],
  },
] satisfies Menu;
